from agents.graph.state import TriageState
from agents.services import github as gh
from shared.config import get_settings
from shared.logging import get_logger

log = get_logger(__name__)


def _render_public_body(state: TriageState) -> str:
    """Render the polished body that gets published to the PUBLIC repo.

    Intentionally omits the raw stack trace and internal fields so nothing sensitive
    leaks even if redaction upstream had a gap. The public issue summarizes; the
    private issue holds the full (already-redacted) payload as an audit trail.
    """
    result = state["result"]
    payload = state["payload"]
    marker = gh.render_fingerprint_marker(result.fingerprint)

    autofix = state.get("autofix")
    autofix_block = ""
    if autofix and autofix.pr_url:
        autofix_block = (
            f"\n## Auto-fix attempt\n\n"
            f"An automated pull request has been opened: {autofix.pr_url}\n"
            f"It is **unreviewed**; merge only after human inspection and CI.\n"
        )
    elif autofix and autofix.skipped_reason:
        autofix_block = (
            f"\n## Auto-fix attempt\n\n"
            f"_Skipped — {autofix.skipped_reason}._\n"
        )

    return f"""{marker}

## Summary
{result.summary or "_no summary_"}

## Root cause hypothesis
{result.root_cause_hypothesis or "_unknown_"}

## Signal

| Field | Value |
| --- | --- |
| Category | `{result.category}` |
| Severity | `{result.severity}` |
| Component (cloud role) | `{payload.cloud_role or "unknown"}` |
| Operation | `{payload.operation or "unknown"}` |
| Fingerprint | `{result.fingerprint}` |
{autofix_block}
---

_Generated by `log-triage-agent`. Exception detail and stack trace remain in the internal triage issue._
"""


def publish_node(state: TriageState) -> TriageState:
    """Publish to public repo, then close the private input issue with a link."""
    result = state["result"]
    private_number = state["issue_number"]
    settings = get_settings()

    # Case 1 — duplicate of an existing public issue: comment on the public one,
    # close the private one.
    if result.is_duplicate and result.duplicate_of:
        gh.comment_output_issue(
            result.duplicate_of,
            f"Another occurrence observed (private #{private_number}, "
            f"fingerprint `{result.fingerprint}`).",
        )
        public_url = f"https://github.com/{settings.output_full_repo}/issues/{result.duplicate_of}"
        gh.close_input_issue(
            private_number,
            link_to_public=public_url,
            reason=f"Duplicate of existing public issue #{result.duplicate_of}.",
        )
        log.info(
            "publish.duplicate_linked",
            private=private_number,
            public=result.duplicate_of,
        )
        return {}

    # Case 2 — new issue: create in public repo, then close private.
    labels = sorted({
        settings.published_label,
        *result.labels,
        f"severity:{result.severity}",
        f"category:{result.category}",
    })

    public_issue = gh.create_output_issue(
        title=result.suggested_title or state.get("issue_title", "Production error"),
        body=_render_public_body(state),
        labels=labels,
    )

    gh.close_input_issue(
        private_number,
        link_to_public=public_issue.html_url,
        reason=f"Published as public issue #{public_issue.number}.",
    )
    log.info(
        "publish.created",
        private=private_number,
        public=public_issue.number,
        fingerprint=result.fingerprint,
        severity=result.severity,
        category=result.category,
    )
    return {}
